export interface ThemeConfig {
  id: string;
  name: string;
  emoji: string;
  bgColor: string;
  textColor: string;
  btnBg: string;
  btnText: string;
  btnBorder: string;
  btnStyle: 'rounded-xl' | 'rounded-full' | 'rounded-none' | 'shadow';
  bgGradient?: string;
}

export const JAPANESE_THEMES: ThemeConfig[] = [
  {
    id: 'sakura',
    name: 'Sakura',
    emoji: '🌸',
    bgColor: '#FFF5F5',
    textColor: '#8C3A4F',
    btnBg: '#FFD6E0',
    btnText: '#8C3A4F',
    btnBorder: '#FFB3C6',
    btnStyle: 'rounded-full',
    bgGradient: 'linear-gradient(135deg, #FFF0F5 0%, #FFE4E1 100%)',
  },
  {
    id: 'tsukiyo',
    name: 'Tsukiyo',
    emoji: '🌙',
    bgColor: '#0B132B',
    textColor: '#F4F4F9',
    btnBg: '#1C2541',
    btnText: '#F4F4F9',
    btnBorder: '#5BC0BE',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #0B132B 0%, #1C2541 100%)',
  },
  {
    id: 'mizukaze',
    name: 'Mizukaze',
    emoji: '🌊',
    bgColor: '#E0F2FE',
    textColor: '#0369A1',
    btnBg: '#BAE6FD',
    btnText: '#0369A1',
    btnBorder: '#7DD3FC',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #E0F7FA 0%, #80DEEA 100%)',
  },
  {
    id: 'aozora',
    name: 'Aozora',
    emoji: '☁️',
    bgColor: '#F0F9FF',
    textColor: '#075985',
    btnBg: '#ffffff',
    btnText: '#075985',
    btnBorder: '#E0F2FE',
    btnStyle: 'shadow',
    bgGradient: 'linear-gradient(180deg, #BAE6FD 0%, #E0F2FE 100%)',
  },
  {
    id: 'kurohana',
    name: 'Kurohana',
    emoji: '🖤',
    bgColor: '#18181B',
    textColor: '#E4E4E7',
    btnBg: '#27272A',
    btnText: '#E4E4E7',
    btnBorder: '#3F3F46',
    btnStyle: 'rounded-none',
  },
  {
    id: 'yuki',
    name: 'Yuki',
    emoji: '❄️',
    bgColor: '#F8FAFC',
    textColor: '#475569',
    btnBg: '#ffffff',
    btnText: '#475569',
    btnBorder: '#E2E8F0',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'momiji',
    name: 'Momiji',
    emoji: '🍁',
    bgColor: '#FDF2F2',
    textColor: '#9B1C1C',
    btnBg: '#FDE8E8',
    btnText: '#9B1C1C',
    btnBorder: '#F8B4B4',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #FEF2F2 0%, #FEE2E2 100%)',
  },
  {
    id: 'ame',
    name: 'Ame',
    emoji: '🌧',
    bgColor: '#ECF1F6',
    textColor: '#2F4F4F',
    btnBg: '#D5E1ED',
    btnText: '#2F4F4F',
    btnBorder: '#C0D2E3',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'kaminari',
    name: 'Kaminari',
    emoji: '⚡',
    bgColor: '#FFFBEB',
    textColor: '#78350F',
    btnBg: '#FEF3C7',
    btnText: '#78350F',
    btnBorder: '#FDE68A',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'hoshi',
    name: 'Hoshi',
    emoji: '⭐',
    bgColor: '#090D16',
    textColor: '#FBBF24',
    btnBg: '#111827',
    btnText: '#FBBF24',
    btnBorder: '#1F2937',
    btnStyle: 'shadow',
  },
  {
    id: 'hinode',
    name: 'Hinode',
    emoji: '🌅',
    bgColor: '#FFF7ED',
    textColor: '#C2410C',
    btnBg: '#FFEDD5',
    btnText: '#C2410C',
    btnBorder: '#FED7AA',
    btnStyle: 'rounded-full',
    bgGradient: 'linear-gradient(135deg, #FFF7ED 0%, #FFEDD5 50%, #FED7AA 100%)',
  },
  {
    id: 'yuuyake',
    name: 'Yuuyake',
    emoji: '🌇',
    bgColor: '#FFF1F2',
    textColor: '#BE123C',
    btnBg: '#FFE4E6',
    btnText: '#BE123C',
    btnBorder: '#FECDD3',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #FFE4E6 0%, #FF8787 100%)',
  },
  {
    id: 'matsuri',
    name: 'Matsuri',
    emoji: '🏮',
    bgColor: '#7A0010',
    textColor: '#FFF5F5',
    btnBg: '#9B1C1C',
    btnText: '#FFF5F5',
    btnBorder: '#E53E3E',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'tanabata',
    name: 'Tanabata',
    emoji: '🎋',
    bgColor: '#ECFDF5',
    textColor: '#065F46',
    btnBg: '#D1FAE5',
    btnText: '#065F46',
    btnBorder: '#A7F3D0',
    btnStyle: 'rounded-full',
  },
  {
    id: 'bamboo',
    name: 'Bamboo',
    emoji: '🎍',
    bgColor: '#F4FBF7',
    textColor: '#1B4332',
    btnBg: '#D8F3DC',
    btnText: '#1B4332',
    btnBorder: '#B7E4C7',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'zen',
    name: 'Zen',
    emoji: '🪨',
    bgColor: '#F5F5F4',
    textColor: '#44403C',
    btnBg: '#E7E5E4',
    btnText: '#44403C',
    btnBorder: '#D6D3D1',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'koi',
    name: 'Koi',
    emoji: '🐟',
    bgColor: '#FFF8F6',
    textColor: '#D9383A',
    btnBg: '#FFF0ED',
    btnText: '#D9383A',
    btnBorder: '#FFD8D4',
    btnStyle: 'shadow',
  },
  {
    id: 'butterfly',
    name: 'Butterfly',
    emoji: '🦋',
    bgColor: '#FAF5FF',
    textColor: '#6B21A8',
    btnBg: '#F3E8FF',
    btnText: '#6B21A8',
    btnBorder: '#E9D5FF',
    btnStyle: 'rounded-full',
    bgGradient: 'linear-gradient(135deg, #FAF5FF 0%, #E9D5FF 100%)',
  },
  {
    id: 'fire',
    name: 'Fire',
    emoji: '🔥',
    bgColor: '#000000',
    textColor: '#F97316',
    btnBg: '#1A1A1A',
    btnText: '#F97316',
    btnBorder: '#EA580C',
    btnStyle: 'rounded-none',
  },
  {
    id: 'wisteria',
    name: 'Wisteria',
    emoji: '💜',
    bgColor: '#FAF5FF',
    textColor: '#5B21B6',
    btnBg: '#F3E8FF',
    btnText: '#5B21B6',
    btnBorder: '#DDD6FE',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #FAF5FF 0%, #D8B4FE 100%)',
  },
];

export function getThemeById(id: string): ThemeConfig | undefined {
  return JAPANESE_THEMES.find((t) => t.id === id);
}
