export interface ThemeConfig {
  id: string;
  name: string;
  emoji: string;
  bgColor: string;
  textColor: string;
  btnBg: string;
  btnText: string;
  btnBorder: string;
  btnStyle: 'rounded-xl' | 'rounded-full' | 'rounded-none' | 'shadow';
  bgGradient?: string;
}

export const JAPANESE_THEMES: ThemeConfig[] = [
  // --- EXISTING THEMES ---
  {
    id: 'sakura',
    name: 'Sakura',
    emoji: '🌸',
    bgColor: '#FFF5F5',
    textColor: '#8C3A4F',
    btnBg: '#FFD6E0',
    btnText: '#8C3A4F',
    btnBorder: '#FFB3C6',
    btnStyle: 'rounded-full',
    bgGradient: 'linear-gradient(135deg, #FFF0F5 0%, #FFE4E1 100%)',
  },
  {
    id: 'tsukiyo',
    name: 'Tsukiyo',
    emoji: '🌙',
    bgColor: '#0B132B',
    textColor: '#F4F4F9',
    btnBg: '#1C2541',
    btnText: '#F4F4F9',
    btnBorder: '#5BC0BE',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #0B132B 0%, #1C2541 100%)',
  },
  {
    id: 'mizukaze',
    name: 'Mizukaze',
    emoji: '🌊',
    bgColor: '#E0F2FE',
    textColor: '#0369A1',
    btnBg: '#BAE6FD',
    btnText: '#0369A1',
    btnBorder: '#7DD3FC',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #E0F7FA 0%, #80DEEA 100%)',
  },
  {
    id: 'aozora',
    name: 'Aozora',
    emoji: '☁️',
    bgColor: '#F0F9FF',
    textColor: '#075985',
    btnBg: '#ffffff',
    btnText: '#075985',
    btnBorder: '#E0F2FE',
    btnStyle: 'shadow',
    bgGradient: 'linear-gradient(180deg, #BAE6FD 0%, #E0F2FE 100%)',
  },
  {
    id: 'kurohana',
    name: 'Kurohana',
    emoji: '🖤',
    bgColor: '#18181B',
    textColor: '#E4E4E7',
    btnBg: '#27272A',
    btnText: '#E4E4E7',
    btnBorder: '#3F3F46',
    btnStyle: 'rounded-none',
  },
  {
    id: 'yuki',
    name: 'Yuki',
    emoji: '❄️',
    bgColor: '#F8FAFC',
    textColor: '#475569',
    btnBg: '#ffffff',
    btnText: '#475569',
    btnBorder: '#E2E8F0',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'momiji',
    name: 'Momiji',
    emoji: '🍁',
    bgColor: '#FDF2F2',
    textColor: '#9B1C1C',
    btnBg: '#FDE8E8',
    btnText: '#9B1C1C',
    btnBorder: '#F8B4B4',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #FEF2F2 0%, #FEE2E2 100%)',
  },
  {
    id: 'ame',
    name: 'Ame',
    emoji: '🌧',
    bgColor: '#ECF1F6',
    textColor: '#2F4F4F',
    btnBg: '#D5E1ED',
    btnText: '#2F4F4F',
    btnBorder: '#C0D2E3',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'kaminari',
    name: 'Kaminari',
    emoji: '⚡',
    bgColor: '#FFFBEB',
    textColor: '#78350F',
    btnBg: '#FEF3C7',
    btnText: '#78350F',
    btnBorder: '#FDE68A',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'hoshi',
    name: 'Hoshi',
    emoji: '⭐',
    bgColor: '#090D16',
    textColor: '#FBBF24',
    btnBg: '#111827',
    btnText: '#FBBF24',
    btnBorder: '#1F2937',
    btnStyle: 'shadow',
  },
  {
    id: 'hinode',
    name: 'Hinode',
    emoji: '🌅',
    bgColor: '#FFF7ED',
    textColor: '#C2410C',
    btnBg: '#FFEDD5',
    btnText: '#C2410C',
    btnBorder: '#FED7AA',
    btnStyle: 'rounded-full',
    bgGradient: 'linear-gradient(135deg, #FFF7ED 0%, #FFEDD5 50%, #FED7AA 100%)',
  },
  {
    id: 'yuuyake',
    name: 'Yuuyake',
    emoji: '🌇',
    bgColor: '#FFF1F2',
    textColor: '#BE123C',
    btnBg: '#FFE4E6',
    btnText: '#BE123C',
    btnBorder: '#FECDD3',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #FFE4E6 0%, #FF8787 100%)',
  },
  {
    id: 'matsuri',
    name: 'Matsuri',
    emoji: '🏮',
    bgColor: '#7A0010',
    textColor: '#FFF5F5',
    btnBg: '#9B1C1C',
    btnText: '#FFF5F5',
    btnBorder: '#E53E3E',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'tanabata',
    name: 'Tanabata',
    emoji: '🎋',
    bgColor: '#ECFDF5',
    textColor: '#065F46',
    btnBg: '#D1FAE5',
    btnText: '#065F46',
    btnBorder: '#A7F3D0',
    btnStyle: 'rounded-full',
  },
  {
    id: 'bamboo',
    name: 'Bamboo',
    emoji: '🎍',
    bgColor: '#F4FBF7',
    textColor: '#1B4332',
    btnBg: '#D8F3DC',
    btnText: '#1B4332',
    btnBorder: '#B7E4C7',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'zen',
    name: 'Zen',
    emoji: '🪨',
    bgColor: '#F5F5F4',
    textColor: '#44403C',
    btnBg: '#E7E5E4',
    btnText: '#44403C',
    btnBorder: '#D6D3D1',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'koi',
    name: 'Koi',
    emoji: '🐟',
    bgColor: '#FFF8F6',
    textColor: '#D9383A',
    btnBg: '#FFF0ED',
    btnText: '#D9383A',
    btnBorder: '#FFD8D4',
    btnStyle: 'shadow',
  },
  {
    id: 'butterfly',
    name: 'Butterfly',
    emoji: '🦋',
    bgColor: '#FAF5FF',
    textColor: '#6B21A8',
    btnBg: '#F3E8FF',
    btnText: '#6B21A8',
    btnBorder: '#E9D5FF',
    btnStyle: 'rounded-full',
    bgGradient: 'linear-gradient(135deg, #FAF5FF 0%, #E9D5FF 100%)',
  },
  {
    id: 'fire',
    name: 'Fire',
    emoji: '🔥',
    bgColor: '#000000',
    textColor: '#F97316',
    btnBg: '#1A1A1A',
    btnText: '#F97316',
    btnBorder: '#EA580C',
    btnStyle: 'rounded-none',
  },
  {
    id: 'wisteria',
    name: 'Wisteria',
    emoji: '💜',
    bgColor: '#FAF5FF',
    textColor: '#5B21B6',
    btnBg: '#F3E8FF',
    btnText: '#5B21B6',
    btnBorder: '#DDD6FE',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #FAF5FF 0%, #D8B4FE 100%)',
  },

  // --- 10 NEW ENTERPRISE & SEASONAL THEMES ---
  {
    id: 'haru_spring',
    name: 'Haru Spring',
    emoji: '🌸',
    bgColor: '#FFF0F3',
    textColor: '#C2185B',
    btnBg: '#FCE4EC',
    btnText: '#C2185B',
    btnBorder: '#F8BBD0',
    btnStyle: 'rounded-full',
    bgGradient: 'linear-gradient(180deg, #FFF5F7 0%, #FFD1DC 100%)',
  },
  {
    id: 'aki_autumn',
    name: 'Aki Autumn',
    emoji: '🍁',
    bgColor: '#FFF3E0',
    textColor: '#E65100',
    btnBg: '#FFE0B2',
    btnText: '#E65100',
    btnBorder: '#FFB74D',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(180deg, #FFF8E1 0%, #FFE0B2 100%)',
  },
  {
    id: 'fuyu_winter',
    name: 'Fuyu Winter',
    emoji: '❄️',
    bgColor: '#E0F7FA',
    textColor: '#006064',
    btnBg: '#B2EBF2',
    btnText: '#006064',
    btnBorder: '#4DD0E1',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(180deg, #E0F7FA 0%, #80DEEA 100%)',
  },
  {
    id: 'natsu_matsuri',
    name: 'Natsu Matsuri',
    emoji: '🏮',
    bgColor: '#1A002C',
    textColor: '#FFD54F',
    btnBg: '#311B92',
    btnText: '#FFD54F',
    btnBorder: '#512DA8',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(180deg, #1A002C 0%, #311B92 100%)',
  },
  {
    id: 'matcha',
    name: 'Matcha Green',
    emoji: '🍵',
    bgColor: '#F1F8E9',
    textColor: '#33691E',
    btnBg: '#DCEDC8',
    btnText: '#33691E',
    btnBorder: '#AED581',
    btnStyle: 'rounded-xl',
  },
  {
    id: 'shinrin_yoku',
    name: 'Shinrin Yoku',
    emoji: '🌲',
    bgColor: '#E8F5E9',
    textColor: '#1B5E20',
    btnBg: '#C8E6C9',
    btnText: '#1B5E20',
    btnBorder: '#A5D6A7',
    btnStyle: 'rounded-full',
  },
  {
    id: 'origami',
    name: 'Origami',
    emoji: '📐',
    bgColor: '#FAFAFA',
    textColor: '#37474F',
    btnBg: '#CFD8DC',
    btnText: '#37474F',
    btnBorder: '#B0BEC5',
    btnStyle: 'rounded-none',
  },
  {
    id: 'shogun',
    name: 'Shogun Gold',
    emoji: '👑',
    bgColor: '#1A1A1A',
    textColor: '#FFD700',
    btnBg: '#2D2D2D',
    btnText: '#FFD700',
    btnBorder: '#DAA520',
    btnStyle: 'shadow',
  },
  {
    id: 'cyber_tokyo',
    name: 'Cyber Tokyo',
    emoji: '🌆',
    bgColor: '#0D0221',
    textColor: '#00F0FF',
    btnBg: '#0F084B',
    btnText: '#00F0FF',
    btnBorder: '#FF007F',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #0D0221 0%, #0F084B 100%)',
  },
  {
    id: 'fuji_sunset',
    name: 'Fuji Sunset',
    emoji: '🗻',
    bgColor: '#FFF3E0',
    textColor: '#4A148C',
    btnBg: '#FFE0B2',
    btnText: '#4A148C',
    btnBorder: '#D1C4E9',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(180deg, #FF7043 0%, #9C27B0 100%)',
  },

  // --- ANIME INSPIRED NEW THEMES ---
  {
    id: 'moonlight_forest',
    name: 'Moonlight Forest',
    emoji: '🌙',
    bgColor: '#0A0E1A',
    textColor: '#B8D4F0',
    btnBg: '#111827',
    btnText: '#B8D4F0',
    btnBorder: '#1E3A5F',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(180deg, #0A0E1A 0%, #0D1B2A 50%, #162032 100%)',
  },
  {
    id: 'galaxy_dream',
    name: 'Galaxy Dream',
    emoji: '✨',
    bgColor: '#0B0014',
    textColor: '#DDD6FE',
    btnBg: '#1E0A3C',
    btnText: '#DDD6FE',
    btnBorder: '#7C3AED',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(135deg, #0B0014 0%, #1E0A3C 50%, #2D1B69 100%)',
  },
  {
    id: 'ocean_sunset',
    name: 'Ocean Sunset',
    emoji: '🌅',
    bgColor: '#FFF3E0',
    textColor: '#7B341E',
    btnBg: '#FED7AA',
    btnText: '#7B341E',
    btnBorder: '#F97316',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(180deg, #FF6B35 0%, #F7B731 40%, #3D9EFF 100%)',
  },
  {
    id: 'bamboo_zen',
    name: 'Bamboo Zen',
    emoji: '🎋',
    bgColor: '#F0FFF4',
    textColor: '#1A4731',
    btnBg: '#C6F6D5',
    btnText: '#1A4731',
    btnBorder: '#68D391',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(180deg, #F0FFF4 0%, #C6F6D5 100%)',
  },
  {
    id: 'sky_kingdom',
    name: 'Sky Kingdom',
    emoji: '☁️',
    bgColor: '#E0F2FE',
    textColor: '#0C4A6E',
    btnBg: '#BAE6FD',
    btnText: '#0C4A6E',
    btnBorder: '#38BDF8',
    btnStyle: 'shadow',
    bgGradient: 'linear-gradient(180deg, #93C5FD 0%, #E0F2FE 60%, #BAE6FD 100%)',
  },
  {
    id: 'shrine_festival',
    name: 'Shrine Festival',
    emoji: '🏮',
    bgColor: '#1A0500',
    textColor: '#FFE5C4',
    btnBg: '#7B1D00',
    btnText: '#FFE5C4',
    btnBorder: '#DC2626',
    btnStyle: 'rounded-full',
    bgGradient: 'linear-gradient(135deg, #1A0500 0%, #7B1D00 100%)',
  },
  {
    id: 'railway_sunset',
    name: 'Railway Sunset',
    emoji: '🚉',
    bgColor: '#FFF7ED',
    textColor: '#92400E',
    btnBg: '#FDE68A',
    btnText: '#92400E',
    btnBorder: '#F59E0B',
    btnStyle: 'rounded-xl',
    bgGradient: 'linear-gradient(180deg, #F97316 0%, #FDE68A 60%, #FFF7ED 100%)',
  },
  {
    id: 'frieren',
    name: 'Wandering Mage',
    emoji: '🪄',
    bgColor: '#1A1220',
    textColor: '#E8D5F5',
    btnBg: '#2D1F40',
    btnText: '#E8D5F5',
    btnBorder: '#7E5BAF',
    btnStyle: 'rounded-full',
    bgGradient: 'linear-gradient(180deg, #1A1220 0%, #2D1F40 50%, #3D2960 100%)',
  },
  {
    id: 'demon_slayer',
    name: 'Crimson Blade',
    emoji: '⚔️',
    bgColor: '#0D0014',
    textColor: '#FFE4E6',
    btnBg: '#1A0022',
    btnText: '#FFE4E6',
    btnBorder: '#E11D48',
    btnStyle: 'rounded-none',
    bgGradient: 'linear-gradient(135deg, #0D0014 0%, #1A0022 40%, #2D0035 100%)',
  },
];

export function getThemeById(id: string): ThemeConfig | undefined {
  return JAPANESE_THEMES.find((t) => t.id === id);
}
